### ISSUE TITLE
Broken test cases

### ISSUE THREAD

**Issue by shelldweller** [django-mptt/django-mptt#352]
I started working on #257 only to find out that lots of tests are failing.

First of all we need to add SECRET_KEY to settings.py: without it I can't run a single test.

Under Django 1.6 / Python 2.7.5:

```
$ ./runtests.sh 
./runtests.sh: line 5: django-admin: command not found
```

Setting up the environment manually and running ```django-admin.py test --pythonpath="../"``` results in 2 doctest failures.

Under Django 1.7 / Python 2.7.5 19 doctests fail:

```
... snap ...
File "myapp/doctests.txt", line 1426, in doctests.txt
Failed example:
    print_tree_details(OrderedInsertion.objects.all())
Expected:
    1 - 1 0 1 6
    2 1 1 1 2 3
    3 1 1 1 4 5
Got:
    43 - 1 0 1 6
    44 43 1 1 2 3
    45 43 1 1 4 5
**********************************************************************
1 items had failures:
  19 of 545 in doctests.txt
***Test Failed*** 19 failures.

F.........
======================================================================
FAIL: test_run_doctest (tests.myapp.tests.DocTestTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "myapp/tests.py", line 54, in test_run_doctest
    self.fail()
AssertionError: None

----------------------------------------------------------------------
Ran 15 tests in 0.589s

FAILED (failures=1)
```

**Comment by shelldweller** [comment]
Form tests fail for me due to attribute order in resulting HTML:
```
Expected:
...
    <tr><th><label for="id_position">Position:</label></th><td><select name="position" id="id_position">
...
Got:
...
    <tr><th><label for="id_position">Position:</label></th><td><select id="id_position" name="position">
...
```
 We need to move those out of doctests and use ```assertHTMLEqual``` instead.

**Comment by shelldweller** [comment]
When executing doctests under Django 1.7 object deletion (e.g., ```OrderedInsertion.objects.all().delete()```) does not reset PK counter and so primary keys keep growing which messes up doctests. I think the quickest fix is to specify object ids explicitly.

**Comment by shelldweller** [comment]
Sorry folks. User error. I had an outdated fork I forgot about and when I forked django-mptt again yesterday Github just silently opened my old fork without updating anything.
