### ISSUE TITLE
Support django manager use_in_migration

### ISSUE THREAD

**Issue by fritz-k** [django-mptt/django-mptt#383]
Django 1.8 added the option to serialize custom managers and use them in migrations. Doing this with the TreeManager currently throws errors due to `mptt_meta` not being available on our model during migration.

```
def contribute_to_class(self, model, name):
...
    self.tree_model = _get_tree_model(model)
...
```
returns `None` because it can't find the `_mptt_meta` attribute on any model. Leading to the error
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/core/management/commands/makemigrations.py", line 125, in handle
    migration_name=self.migration_name,
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/migrations/autodetector.py", line 43, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/migrations/autodetector.py", line 111, in _detect_changes
    self.new_apps = self.to_state.apps
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/utils/functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/migrations/state.py", line 166, in apps
    return StateApps(self.real_apps, self.models)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/migrations/state.py", line 232, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/migrations/state.py", line 262, in render_multiple
    model.render(self)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/migrations/state.py", line 546, in render
    body,
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/models/base.py", line 189, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/models/base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/mptt/managers.py", line 81, in contribute_to_class
    self._base_manager = self.tree_model._tree_manager
AttributeError: 'NoneType' object has no attribute '_tree_manager'
```
Substitunging `model` directly for the `_get_tree_model()` function call leads to similar errors:
```
  Applying accounting.0003_create_account_tree...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/fritz/projekte/intranet/accounting/migrations/0003_create_account_tree.py", line 105, in create_accounts
    l0 = Account.objects.create(name=root_name, group=group)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/mptt/managers.py", line 99, in get_queryset
    return qs.order_by(self.tree_id_attr, self.left_attr)
  File "/home/fritz/.pyvenvs/intranet/lib/python3.4/site-packages/mptt/managers.py", line 360, in tree_id_attr
    return self.model._mptt_meta.tree_id_attr
AttributeError: type object 'Account' has no attribute '_mptt_meta'
```

Is there a way around this problem? It'd be great to have TreeManager available within migrations.

**Comment by craigds** [comment]
closing in favour of #382
