### ISSUE TITLE
mptt.register(order_insertion_by=[ORDER]) not working when ORDER is UTF

### ISSUE THREAD

**Issue by prudnitskiy** [django-mptt/django-mptt#446]
Saw this problem on newest versions:

```
#example model code:

@python_2_unicode_compatible
Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

TreeForeignKey(Category,
               blank=True,
               null=True,
               db_index=True,
               related_name='children').contribute_to_class(Category, 'parent')

mptt.register(Category, order_insertion_by=['name'])
```

Next, trying to get tree:

```
>>> get_cached_trees(Category.objects.all())
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/virtualenv/ve-XXXXX/local/lib/python2.7/site-packages/mptt/utils.py", line 240, in get_cached_trees
    _('Node %s not in depth-first order (%d < %d) %d') % (type(queryset), node_level, root_level, obj.pk)
ValueError: Node <class 'django.db.models.query.QuerySet'> not in depth-first order (0 < 1) 1
```

But get_cached_trees will work fine when you reorder it:
```
>>>  get_cached_trees(Category.objects.all().order_by("ok")
```

Software used:
* django 1.9.4 (1.8.11 also have this problem)
* django-mptt 0.8.3
* DB postgresql 9.4
* psycopg 2.6.1

**Comment by craigds** [comment]
What's `Category._meta.ordering` ?

**Comment by prudnitskiy** [comment]
```
>>> Category._meta.ordering
[]
```

**Comment by craigds** [comment]
Just to clarify, sounds like the bug is just that `register()` should set `_meta.ordering` but doesn't.

**Comment by matthiask** [comment]
Ah, interesting. The assignment of (tree_id,lft) to `_meta.ordering` has been removed by yours truly (https://github.com/django-mptt/django-mptt/commit/0406a736b33e7f599dea3688d4d2cc08ac469fc0), but I don't completely understand (yet) what my thinking was.

The default manager (yay! managers!) should always ensure that the ordering of querysets is correct. But maybe that one isn't used at all here...

This might be the simplest fix, but it does not feel right since we override `get_queryset` exactly for this, and also because of missing tests.

```
diff --git a/mptt/managers.py b/mptt/managers.py
index 724ccb7..d2eb873 100644
--- a/mptt/managers.py
+++ b/mptt/managers.py
@@ -88,6 +88,8 @@ class TreeManager(models.Manager.from_queryset(TreeQuerySet)):
                 # _base_manager is the treemanager on tree_model
                 self._base_manager = self.tree_model._tree_manager
 
+            model._meta.ordering = (self.tree_id_attr, self.left_attr)
+
     def get_queryset(self, *args, **kwargs):
         """
         Ensures that this manager always returns nodes in tree order.
```

@prudnitskiy Can you verify whether `TreeManager.get_queryset()` is called at all in your example?

**Comment by matthiask** [comment]
Setting `_meta.ordering` was intentionally removed; the `TreeManager.get_queryset()` override applies tree ordering to every queryset produced by the default manager. If there is a specific case where ordering is not applied, please open a new issue with a reproducible example. See also #833.
