### ISSUE TITLE
ImportError: No module named util (Django 1.9.5)

### ISSUE THREAD

**Issue by andreyugit** [django-mptt/django-mptt#457]
Unhandled exception in thread started by <function wrapper at 0xa431dbc>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/mptt/models.py", line 14, in <module>
    from mptt.fields import TreeForeignKey, TreeOneToOneField, TreeManyToManyField
  File "/usr/local/lib/python2.7/dist-packages/mptt/fields.py", line 9, in <module>
    from mptt.forms import TreeNodeChoiceField, TreeNodeMultipleChoiceField
  File "/usr/local/lib/python2.7/dist-packages/mptt/forms.py", line 7, in <module>
    from django.forms.util import ErrorList
ImportError: No module named util

What is the problem?

**Comment by craigds** [comment]
Looks like you're using an old version of django-mptt. This was fixed in 4ea3137280cd47716d55e1aa68d222dd61bd329b which is in 0.7+
