### ISSUE TITLE
Django 1.10 support: can't set attribute _default_manager at startup

### ISSUE THREAD

**Issue by mlorant** [django-mptt/django-mptt#469]
While testing Django 1.10, mptt seems to mess with internal API of the framework, that has changed since 1.9. Here's the stacktrace I get at the loading of `manage.py runserver`:

```
$ ./manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x7f32e681faa0>
Traceback (most recent call last):
  File "My_VENV/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "My_VENV/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "My_VENV/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "My_VENV/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "My_VENV/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "My_VENV/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "My_VENV/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "My_VENV/lib/python2.7/site-packages/mptt/models.py", line 379, in <module>
    class MPTTModel(six.with_metaclass(MPTTModelBase, models.Model)):
  File "My_VENV/lib/python2.7/site-packages/django/utils/six.py", line 808, in __new__
    return meta(name, bases, d)
  File "My_VENV/lib/python2.7/site-packages/mptt/models.py", line 262, in __new__
    cls = super_new(meta, class_name, bases, class_dict)
  File "My_VENV/lib/python2.7/site-packages/django/db/models/base.py", line 157, in __new__
    new_class.add_to_class(obj_name, obj)
  File "My_VENV/lib/python2.7/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "My_VENV/lib/python2.7/site-packages/mptt/managers.py", line 81, in contribute_to_class
    super(TreeManager, self).contribute_to_class(model, name)
  File "My_VENV/lib/python2.7/site-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute
```

In `contribute_to_class` (the method in Django file), arguments are `model=<class 'mptt.models.MPTTModel'> name=_default_manager`. It looks like `_default_manager` is now read only.

It might be linked to the following change ([from the release notes](https://docs.djangoproject.com/en/dev/releases/1.10/)):
> The new Meta.base_manager_name and Meta.default_manager_name options allow controlling the _base_manager and _default_manager, respectively.

**Comment by claudep** [comment]
See also:
https://code.djangoproject.com/ticket/20932
https://github.com/django/django/commit/3a47d42fa33012
https://github.com/django/django/commit/ed0ff913c648b16

**Comment by ad-m** [comment]
I did bisect.
```
3a47d42fa33012b2156bf04058d933df6b3082d2 is the first bad commit
commit 3a47d42fa33012b2156bf04058d933df6b3082d2
Author: Loïc Bistuer <loic.bistuer@gmail.com>
Date:   Fri Feb 19 02:27:55 2016 +0700

    Fixed #20932, #25897 -- Streamlined manager inheritance.

:040000 040000 38d13fce93afd45e6af895cbdae6b0cb9eb6ca68 366dea9a0188cf3f13c488af0231bf4409496a4d M	django
:040000 040000 de931578d9561cea24c80280e60a3c3e37f404ee fc7b316180077a9a64c4dacb7537b64c68bcc603 M	docs
:040000 040000 c9287341cca9444417829522e22f30fcd73a04a3 5fa4e2b8fa8edf814b3fcb1cd4aaf8e2bf64ea20 M	tests
bisect run success
```
https://github.com/django/django/commit/3a47d42fa33012b2156bf04058d933df6b3082d2

**Comment by craigds** [comment]
OK. The cause of that will be https://github.com/django-mptt/django-mptt/blob/master/mptt/models.py#L384

I'm not 100% clear on how best to fix it. 

What about this?
```
class MPTTModel(...):
    objects = TreeManager()
    class MPTTMeta:
        tree_manager_name = 'objects'
```
and subclasses can override one/both of those if they really want to. Then `_tree_manager` just becomes a property wrapped `getattr(cls, cls._mptt_meta.tree_manager_name)`

That seems like the simplest fix and also seems stylistically in line with the changes in Django 1.10, though I'm not very familiar with the whole thing.

**Comment by claudep** [comment]
@loic any input?

**Comment by loic** [comment]
@craigds's proposal looks good to me.

`_tree_manager ` could also do [like we do for `_base_manager`](https://github.com/django/django/commit/ed0ff913c648b16#diff-98e98c694c90e830f918eb5279134ab9R432) and return an instance of `TreeManager` if `tree_manager_name` isn't provided.

**Comment by burakk** [comment]
Is there any progress? How can we solve this issue?

**Comment by mlorant** [comment]
The proposal made above works indeed (I continue my tests with Django 1.10 by patching my local version) but if someone can write a PR, it would speed up the process :-)

**Comment by matthiask** [comment]
@mlorant Can you post a diff here of your changes? That would be very helpful for preparing a PR. Thanks!

**Comment by mlorant** [comment]
@matthiask Don't have time for posting a PR, but the fix is simple and transparent for the user (if you don't want to rename the manager at least):
```
--- a/mptt/models.py
+++ b/mptt/models.py
@@ -379,10 +379,10 @@ class VatRateTest(TestCase):
class MPTTModel(six.with_metaclass(MPTTModelBase, models.Model)):
    """
    Base class for tree models.
    """
-   _default_manager = TreeManager()
+   objects = TreeManager()
+   class MPTTMeta:
+       tree_manager_name = 'objects'

    class Meta:
        abstract = True
```

**Comment by matthiask** [comment]
I'm pursuing a different avenue for fixing this right now:

- Require that `_default_manager` always is a `TreeManager` instance.
- Do not touch `_base_manager` at all.
- Remove as much code as possible, especially metaclass code.
- Probably break backwards compatibility, maybe even with Django 1.8 (this might be a deal breaker because 1.8 is a LTS release. Maybe it makes sense to declare mptt 0.8.x as a LTS release as well, at least if *someone* finds the time, energy and maybe money to actually do the supporting — I'm not too interested in 1.8 anymore because a few of my OSS projects already depend on 1.9...)

The Travis build does not look too bad (https://travis-ci.org/matthiask/django-mptt/builds/144258846). Everything's red, yeah, but with Django 1.9 there aren't many problems left.

**Comment by karolyi** [comment]
+1, subscribing as this bug needs to be addressed.

**Comment by MHM5000** [comment]
Is this gonna be fixed any soon?

**Comment by dpineiden** [comment]
Me too with the problem here...

`Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f35c9e786a8>
Traceback (most recent call last):
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/mptt/models.py", line 385, in <module>
    class MPTTModel(six.with_metaclass(MPTTModelBase, models.Model)):
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/utils/six.py", line 808, in __new__
    return meta(name, bases, d)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/mptt/models.py", line 263, in __new__
    cls = super_new(meta, class_name, bases, class_dict)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/db/models/base.py", line 157, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/mptt/managers.py", line 82, in contribute_to_class
    super(TreeManager, self).contribute_to_class(model, name)
  File "/home/david/.virtualenvs/mjd/lib/python3.4/site-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute
`

**Comment by matthiask** [comment]
If you want to help, please take [django-mptt-nomagic](https://pypi.python.org/pypi/django-mptt-nomagic/) for a test drive and report back any problems you have (and maybe also success — if any). It contains the changes from my pull request https://github.com/django-mptt/django-mptt/pull/486.

I'm running the code in production on a few sites, and am still finding minor bugs from time to time, but since the test suite passes I'm quite confident that the root cause of the problems we're having are not in django-mptt itself.

**Comment by johndeng** [comment]
@matthiask The django-mptt-nomagic has another problem..

```
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute
```

**Comment by mlorant** [comment]
@johndeng Please put the full traceback (at least on django-mptt code part) to be able to debug it efficiently. It would be even better if you can provide a full example of when the following happens.

**Comment by matthiask** [comment]
@johndeng If that still happens you'll first have to 

`pip uninstall -y django-mptt; pip uninstall -y django-mptt-nomagic`

then install django-mptt-nomagic again.

**Comment by johndeng** [comment]
@matthiask I'm followed your guide, and it still happens..

I'm working at Django 1.10..

The full traceback

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/core/management/commands/test.py", line 72, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/test/runner.py", line 549, in run_tests
    old_config = self.setup_databases()
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/test/runner.py", line 499, in setup_databases
    self.parallel, **kwargs
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/test/runner.py", line 743, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 70, in create_test_db
    run_syncdb=True,
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 202, in handle
    targets, plan, fake=fake, fake_initial=fake_initial
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 97, in migrate
    state = self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 132, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 237, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/migrations/migration.py", line 119, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 90, in state_forwards
    list(self.managers),
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/migrations/state.py", line 93, in add_model
    self.reload_model(app_label, model_name)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/migrations/state.py", line 162, in reload_model
    self.apps.render_multiple(states_to_be_rendered)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/migrations/state.py", line 277, in render_multiple
    model.render(self)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/migrations/state.py", line 559, in render
    body,
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/models/base.py", line 157, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/John/Projects/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute
```

**Comment by andrewmarconi** [comment]
@matthiask I just rebuilt my app, upgrading from Django 1.9.9 to 1.10 under Python 3.6, and switched to django-mptt-nomagic. Success. No problems seen.

**Comment by matthiask** [comment]
@andrewmarconi Awesome!

@johndeng It might be that one of your dependencies pulls in the official django-mptt version. Does django-mptt still appear in the `pip freeze -l` output? If yes, did you try rebuilding the virtualenv from the ground up?

**Comment by johndeng** [comment]
@matthiask Problem resolved, because I deleted all database migration file.

**Comment by karolyi** [comment]
@andrewmarconi python3.6?

**Comment by matthiask** [comment]
@karolyi Still alpha, but yes. https://docs.python.org/3.6/whatsnew/3.6.html

**Comment by andrewmarconi** [comment]
Yep, @karolyi ... I like living on the edge. ;)

```
$ python --version
Python 3.6.0a3

$ pip freeze
candybar==0.1.5
Django==1.10
django-bootstrap3==7.0.1
django-cleanup==0.4.2
django-extensions==1.7.1
django-grappelli==2.8.1
django-mptt-nomagic==0.2.2
docopt==0.6.2
jedi==0.9.0
Pillow==3.3.0
prompt-toolkit==1.0.5
psycopg2==2.6.2
ptpython==0.35
Pygments==2.1.3
six==1.10.0
wcwidth==0.1.7
Werkzeug==0.11.10
```

**Comment by lwm** [comment]
> Yep, @karolyi ... I like living on the edge. ;)

```
happy = ";)"
f"I like living on the edge. {happy}"
```

**Comment by sweaver360** [comment]
Hi, do you have any idea when 0.8.6 will be released?  I'm trying to update to Django 1.10 but I can't until this bug fix gets published.  Thanks.

**Comment by shamanis** [comment]
Python 3.4.2, Django 1.10, mptt 0.8.5

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f73c307c158>
Traceback (most recent call last):
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/filer/models/__init__.py", line 3, in <module>
    from .clipboardmodels import *  # flake8: noqa
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/filer/models/clipboardmodels.py", line 9, in <module>
    from . import filemodels
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/filer/models/filemodels.py", line 18, in <module>
    from .foldermodels import Folder
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/filer/models/foldermodels.py", line 240, in <module>
    mptt.register(Folder)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/mptt/__init__.py", line 12, in register
    from mptt.models import MPTTModelBase
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/mptt/models.py", line 385, in <module>
    class MPTTModel(six.with_metaclass(MPTTModelBase, models.Model)):
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/utils/six.py", line 808, in __new__
    return meta(name, bases, d)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/mptt/models.py", line 263, in __new__
    cls = super_new(meta, class_name, bases, class_dict)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/db/models/base.py", line 157, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/mptt/managers.py", line 82, in contribute_to_class
    super(TreeManager, self).contribute_to_class(model, name)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute
```

**Comment by matthiask** [comment]
@craigds Are you planning to roll a release soon-ish? Or is there some blocker I'm not aware of?

**Comment by craigds** [comment]
no blockers, I'll try and get this done today

**Comment by sweaver360** [comment]
I just upgraded to 0.8.6 and Django 1.10.  My server runs, but I get the following error when I attempt to run migrations:

`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 202, in handle
    targets, plan, fake=fake, fake_initial=fake_initial
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 97, in migrate
    state = self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 138, in _migrate_all_forwards
    migration.mutate_state(state, preserve=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 92, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 733, in state_forwards
    state.reload_model(app_label, self.name_lower)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/state.py", line 162, in reload_model
    self.apps.render_multiple(states_to_be_rendered)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/state.py", line 277, in render_multiple
    model.render(self)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/state.py", line 559, in render
    body,
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 157, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute`

I added print statements to debug django/db/models/manager.py, and the model that ultimately throws the exception is one that inherits from MPTTModel.  @craigds do you think this is related, or should I open a new ticket for this?

**Comment by matthiask** [comment]
Copying the latest comment from https://github.com/django-mptt/django-mptt/pull/498 here:

Well, the problem will still show for old migrations. I just had to regenerate a migration as well (thanks, sed -e s/_default_manager/objects/) when upgrading to Django 1.10. There's no way to fix broken migrations (caused by mptt) in users' code unfortunately.

@sweaver360 We unfortunately can't fix old migrations; replace _default_manager with objects in your migrations, and things should hopefully work.

**Comment by sweaver360** [comment]
@matthiask thanks, that fixed it!

**Comment by karolyi** [comment]
@matthiask if there is a way to highlight that to the devs upgrading django & mptt, that should be eligible imo.

**Comment by craigds** [comment]
^ Added that to the upgrade notes. See http://django-mptt.github.io/django-mptt/upgrade.html

Hopefully that helps?

**Comment by matthiask** [comment]
@craigds Thanks! I think the change mostly concerns the AlterModelManagers operation; the necessary change in my migration was:

```
diff --git a/app/pages/migrations/0010_auto_20160621_1558.py b/app/pages/migrations/0010_auto_20160621_1558.py
index dd134a4..6433e72 100644
--- a/app/pages/migrations/0010_auto_20160621_1558.py
+++ b/app/pages/migrations/0010_auto_20160621_1558.py
@@ -17,7 +17,7 @@ class Migration(migrations.Migration):
         migrations.AlterModelManagers(
             name='page',
             managers=[
-                ('_default_manager', django.db.models.manager.Manager()),
+                ('objects', django.db.models.manager.Manager()),
             ],
         ),
         migrations.AddField(
```

With some Google-Fu people will certainly find the solution now (I hope)

**Comment by quangv** [comment]
@matthiask Thanks! that solved my `./manage.py test` issues.

**Comment by manikos** [comment]
Mine too! Thanks!

**Comment by jmny** [comment]
> ^ Added that to the upgrade notes. See http://django-mptt.github.io/django-mptt/upgrade.html
> 
> Hopefully that helps?

404, the new url is : 
https://django-mptt.readthedocs.io/en/latest/upgrade.html
