### ISSUE TITLE
IntegrityError when bulk creating instances

### ISSUE THREAD

**Issue by OskarPersson** [django-mptt/django-mptt#560]
When I try to bulk create instances of the model below I get an exception, is this behaviour expected?

```
class MyModel(MPTTModel):
    id = models.IntegerField(primary_key=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
```

```
>>> m1 = MyModel(id=1)                                                                                                                     
>>> m2 = MyModel(id=2, parent=m1)                                                                                                                         
>>> m3 = MyModel(id=3, parent=m1)
>>> l =  [m1, m2, m3] 
>>> MyModel.objects.bulk_create(l)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/Oskar/.pyenv/versions/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/Oskar/.pyenv/versions/venv/lib/python2.7/site-packages/django/db/models/query.py", line 449, in bulk_create
    self._batched_insert(objs_with_pk, fields, batch_size)
  File "/Users/Oskar/.pyenv/versions/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1066, in _batched_insert
    self._insert(item, fields=fields, using=self.db)
  File "/Users/Oskar/.pyenv/versions/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1043, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/Oskar/.pyenv/versions/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/Users/Oskar/.pyenv/versions/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/Oskar/.pyenv/versions/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/Oskar/.pyenv/versions/venv/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/Oskar/.pyenv/versions/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/Oskar/.pyenv/versions/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: NOT NULL constraint failed: mymodel_mymodel.lft
```

**Comment by murdav** [comment]
Let me say yes.
Check also this: https://github.com/django-mptt/django-mptt/issues/277#issuecomment-147550257
Big problems will come if you will use concurrency.

D

**Comment by matthiask** [comment]
Yes, this is expected since the fields are filled in by Python code. 

You could set all mptt attributes to zero and `.objects.rebuild()` the tree after the insertion, or help get #575 moving.

**Comment by Bialomazur** [comment]
Any Updates on this issue?
