### ISSUE TITLE
Field '_order' doesn't have a default value

### ISSUE THREAD

**Issue by fyaconiello** [django-mptt/django-mptt#574]
I am getting the following error when saving MPTT models since I updated

package versions:
django-mptt==0.8.7
Django==1.11

The issue appears to be with one of the mptt default fields `_order`

```
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
                  response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
                  return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
                      response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
          response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
              return view(request, *args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/reversion/admin.py", line 170, in add_view
              return super(VersionAdmin, self).add_view(request, form_url, extra_context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1508, in add_view
          return self.changeform_view(request, None, form_url, extra_context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
              return bound_func(*args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
                      response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
                  return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1408, in changeform_view
              return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1448, in _changeform_view
                  self.save_model(request, new_object, form, not add)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 979, in save_model
          obj.save()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/mptt/models.py", line 993, in save
              super(MPTTModel, self).save(*args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 806, in save
                         force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 836, in save_base
              updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 922, in _save_table
              result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 961, in _do_insert
                                 using=using, raw=raw)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
                  return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 1060, in _insert
          return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1099, in execute_sql
                  cursor.execute(sql, params)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
                  return self.cursor.execute(sql, params)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
                  six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
                  return self.cursor.execute(sql, params)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
              return self.cursor.execute(query, args)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
              self.errorhandler(self, exc, value)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
      raise errorclass, errorvalue
django.db.utils.OperationalError(1364, "Field '_order' doesn't have a default value")
```

**Comment by craigds** [comment]
mptt doesn't have a `_order` field, so I suspect this is caused by some other app/model.

**Comment by matthiask** [comment]
See #833 — I want to keep the project working for the time being but I'm not going to add (and maintain) new features. Thanks for your understanding.
