### ISSUE TITLE
Django 2

### ISSUE THREAD

**Issue by elcolie** [django-mptt/django-mptt#599]
```python
class Category(MPTTModel, AbstractModelController):
    """Directory is shorter than class name to save monitor area"""

    type = models.PositiveSmallIntegerField(choices=StaticCategories.service_type_choices,
                                            verbose_name=_("Service Type"))
    sequence = models.PositiveSmallIntegerField(default=0, db_index=True, verbose_name=_('Sequence'))
    name = models.CharField(max_length=255, blank=False, unique=True)
    header_image = models.ImageField(upload_to='foto/header_image', height_field=None, width_field=None, max_length=100,
                                     blank=True,
                                     null=True)
    content_image = models.ImageField(upload_to='foto/content_image', height_field=None, width_field=None,
                                      max_length=100, blank=True,
                                      null=True)
    popup_image = models.ImageField(upload_to='foto/popup_image', height_field=None, width_field=None, max_length=100,
                                    blank=True,
                                    null=True)
    attribute = JSONField(default={})
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return f"{self.name}"
```

With `Django2` I got error
```bash
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/el/.pyenv/versions/soken3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/el/.pyenv/versions/soken3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/el/.pyenv/versions/soken3.7/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/el/.pyenv/versions/soken3.7/lib/python3.7/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/el/.pyenv/versions/soken3.7/lib/python3.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/el/.pyenv/versions/3.7-dev/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 679, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/el/Code/norak-cutter/soken/soken-web/soken_web/apps/categories/models.py", line 41, in <module>
    class Category(MPTTModel, AbstractModelController):
  File "/Users/el/Code/norak-cutter/soken/soken-web/soken_web/apps/categories/models.py", line 58, in Category
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```
What is the best `on_delete` option for me?

**Comment by matthiask** [comment]
The previous default behavior was `on_delete=models.CASCADE`. It probably is mostly fine, but it really depends on your specific use case.

**Comment by elcolie** [comment]
Thanks. I think so.
