### ISSUE TITLE
Pagination vs. depth-first order

### ISSUE THREAD

**Issue by gpruss** [django-mptt/django-mptt#712]
Hi guys,
I'm having trouble with the pagination of a MPTT model's ListView. It seems my issue boils down to this: If the first item on a page is a root node, everything is fine. If the first item on a page is a child node, I get an error: "Node <class 'mptt.querysets.TreeQuerySet'> not in depth-first order". I am using a pretty standard ListView and only have items of level 0 or 1.
I'm under the impression that I am missing something really basic here and would appreciate a nudge in the right direction.

Cheers,
Gunnar

**Comment by gpruss** [comment]
Hi again,
I created a new project from scratch to dissect the issue and it occurs with Django 2.2.5 and MPTT 0.10.0, too. The ingredients for the issue are:
- a MPTTModel
- a ListView with pagination for that model
- a page that starts with a child node (whose parent is one the previous page) which is followed by a root node.

Please note that the pages before and after the problem might be displayed properly - yikes!

best regards,
Gunnar

**Comment by gpruss** [comment]
Dear all,
this is still troubling me. Is there someone who can reproduce the error? Do I need to add a more specific example? I'd really like to help, but I'm not sure how to...

Cheers,
Gunnar

**Comment by matthiask** [comment]
Do you have a full traceback somewhere? That might be helpful. I have an idea what happens, but it would be easier to confirm this with a traceback.

**Comment by gpruss** [comment]
Hi Matthias,
I hope this is what you had in mind. If you need something else, please let me know. Many thanks in advance!

Internal Server Error: /samples/
Traceback (most recent call last):
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/mptt/templatetags/mptt_tags.py", line 259, in render
    roots = cache_tree_children(queryset)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/mptt/templatetags/mptt_tags.py", line 238, in cache_tree_children
    return get_cached_trees(queryset)
  File "/home/gunnar/virtual_environments/dbGM/lib/python3.7/site-packages/mptt/utils.py", line 251, in get_cached_trees
    _('Node %s not in depth-first order') % (type(queryset),)
ValueError: Node <class 'mptt.querysets.TreeQuerySet'> not in depth-first order

**Comment by gpruss** [comment]
Dear All,
dear Matthias,
I'm still struggling with this. Any suggestions how to fix it?

With best regards,
Gunnar

**Comment by matthiask** [comment]
@gpruss The `recursetree` tag cannot be used together with pagination. 

If you want to show the depth/level of individual nodes in a paginated list I'd use the `level` attribute. 

If you really need some sort of paginated list while still using more of Django MPTT you could take a look at https://github.com/feincms/feincms/blob/86277fe077ce426e50b8aae106a6d5940efb087c/feincms/admin/tree_editor.py#L162-L186 -- but since you're using pagination at all that's probably not exactly what you want (since it includes additional nodes in the final output)

**Comment by gpruss** [comment]
Oh, what a bummer! I'll try to work my way around then.
Thanks, anyway,
Gunnar

**Comment by labohkip81** [comment]
Had this issue. but i upgraded to version 0.11.0. I think its fixed there.

**Comment by matthiask** [comment]
This is a known limitation: `{% recursetree %}` relies on `get_cached_trees()`, which requires the queryset to be a complete subtree in depth-first order. Pagination slices the queryset at an arbitrary point, so a page starting with a child whose parent is on the previous page raises `ValueError: Node not in depth-first order`.

The workaround is to render as a flat list and use `node.level` for indentation. Added a note to the `recursetree` docs. See also #833.
