### ISSUE TITLE
DraggableMPTTAdmin -  Cannot serialize hashid object

### ISSUE THREAD

**Issue by anjalichaudhary** [django-mptt/django-mptt#722]
- Created an admin for my model using DraggableMPTTAdmin.
- It worked with normal id's 
- when changed the id's from int to hashid object it started breaking. Following is the Stack trace :
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
return self.admin_site.admin_view(view)(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
return view(request, *args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/mptt/admin.py", line 162, in changelist_view
self._tree_context(request), cls=DjangoJSONEncoder
File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
**kw).encode(obj)
File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "/usr/local/lib/python3.7/site-packages/django/core/serializers/json.py", line 104, in default
return super().default(o)
File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.__class__.__name__} '

**Comment by matthiask** [comment]
Django's JSON encoder does not seem to support hashids. This is a known problem: https://github.com/nshafer/django-hashid-field/issues/11

We should probably provide a hook in django-mptt to replace the JSON encoder. Do you want to try fixing this @anjalichaudhary ?

**Comment by anjalichaudhary** [comment]
Sure @matthiask I will try to look into this issue. Let me know if you have any suggestions regarding this issue.

**Comment by matthiask** [comment]
@anjalichaudhary I think I'd change `DraggableMPTTAdmin.changelist_view` to call `self._tree_context_json`, a new method which calls `self._tree_context` and returns the serialized JSON String. 

This would allow you to override `_tree_context_json` in your project with a custom DjangoJSONEncoder subclass which understands hashid objects.

**Comment by anjalichaudhary** [comment]
@matthiask I solved the issue. It is working for me locally.  I will make a pull request for the same.
Thankyou

**Comment by anjalichaudhary** [comment]
For someone who wants to do it locally - 

- override changelist_view in your class that subclasses DraggableMPTTAdmin
- copy the code of changelist_view
- create a custom_encoder_class subclassing DjangoJSONEncoder and following what is mentioned by [Bartvds](https://github.com/Bartvds)  - > [here](https://github.com/nshafer/django-hashid-field/issues/11#issue-245081863)
- replace DjangoJSONEncoder with your custom_encoder_class in your chanelist_view.

**Comment by matthiask** [comment]
See #833 — I want to keep the project working for the time being but I'm not going to add (and maintain) new features. Thanks for your understanding.
