### ISSUE TITLE
Please add django 3 support

### ISSUE THREAD

**Issue by ashdaily** [django-mptt/django-mptt#769]
The `django.utils import six` was removed in django 3.0. 
Here is the error i am getting:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/mptt/models.py", line 11, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/usr/local/lib/python3.7/dist-packages/django/utils/__init__.py)
```
Looks like it can be fixed using `pip3 install six`

**Comment by matthiask** [comment]
six has been dropped in 7ec41ab0b60c2cd9f2e3e82dd157ae231d77340f. You are using a outdated version of django-mptt.

**Comment by ashdaily** [comment]
> six has been dropped in [7ec41ab](https://github.com/django-mptt/django-mptt/commit/7ec41ab0b60c2cd9f2e3e82dd157ae231d77340f). You are using a outdated version of django-mptt.

Thanks for quick reply. 
I'll upgrade. Cheers !
