### ISSUE TITLE
ValueError at /admin/{my_app}/{my_node_model}/add/ Cannot call get_descendants on unsaved {my_node_model} instances

### ISSUE THREAD

**Issue by cecilia-cobalt** [django-mptt/django-mptt#779]
Hi! I'm new to the mptt package. Ran into the following issue and could you check if my suggested fix make sense or could it be me missing some local configs to make it work as expected?

`Changeform view` is raising exception on an `MPTTModel`. Under my admin view, I used `DraggableMPTTAdmin`. 

```
Traceback (most recent call last):
  File "lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "lib/python3.6/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "lib/python3.6/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "lib/python3.6/site-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "lib/python3.6/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "lib/python3.6/site-packages/django/contrib/admin/options.py", line 1594, in _changeform_view
    form = ModelForm(initial=initial)
  File "lib/python3.6/site-packages/mptt/forms.py", line 178, in __init__
    pk__in=instance.get_descendants(include_self=True).values_list(
  File "lib/python3.6/site-packages/mptt/models.py", line 419, in _fn
    % {"function": func.__name__, "class": self.__class__.__name__}
 ```
 
 After looking at the `mptt.forms.MPTTAdminForm`, the issue seems to be at [this line](https://github.com/django-mptt/django-mptt/blob/017c591c6ed2c43281ee2eba6b464c719578fc1d/mptt/forms.py#L171). Should it be the following instead?
 
 ```
 self.instance and self.instance.pk and not self.instance._state.adding:
 ```
The changelist view does seem to give the instance a pk value as well, even though at that point the instance has never been saved.

Thank you!

**Comment by yswtrue** [comment]
same error here

**Comment by yswtrue** [comment]
`0.11.0` works fine here

**Comment by cecilia-cobalt** [comment]
> `0.11.0` works fine here

Thank you! Just tried downgrading and it seems to be working fine on `0.11.0` indeed.

**Comment by n4l5u0r** [comment]
issue linked to 0.12 version : to track

**Comment by matthiask** [comment]
The `MPTTAdminForm.__init__` already guards against this with `self.instance.pk and not self.instance._state.adding` — this should have been fixed somewhere between 0.11 and the current version. If you can still reproduce on a current version please open a new issue with a minimal reproduction. See also #833.
